// Temporary, isolated data for manual browser QA. Never uses the shop database.
const express = require('express');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { PostStore } = require('../dist/posts.js');
const { mountPostRoutes } = require('../dist/post-routes.js');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'saximi-news-preview-'));
const store = new PostStore(path.join(dir, 'posts.json'));
for (let i = 0; i < 25; i++) store.save({ title: `Bài kiểm thử ${i + 1}: Thông tin dành cho khách hàng Saximi Shop`, category: ['news', 'event', 'promotion', 'policy'][i % 4], status: 'published', cover: '/icon.png', content: '<h2>Thông tin bài viết</h2><p>Đây là dữ liệu kiểm thử giao diện riêng, không xuất bản lên website chính thức.</p><ul><li>Thông tin tài khoản</li><li>Theo dõi đơn hàng</li></ul>', excerpt: 'Nội dung thử để kiểm tra bố cục, ngày đăng, hình ảnh, chuyên mục và cuộn tải thêm bài viết.' });
const root = path.resolve(__dirname, '../..');
const app = express(); app.use(express.json());
app.get('/shell', (_req, res) => res.type('html').send(fs.readFileSync(path.join(root, 'www/index.html'), 'utf8').replace('<head>', '<head><base href="/">')));
app.get('/api/settings', (_req, res) => res.json({ shopName: 'Saximi Shop', publicSiteUrl: 'http://127.0.0.1:5188' }));
app.get('/api/admin/media-library', (_req, res) => res.json([{ id: 1, title: 'Ảnh kiểm thử', url: '/icon.png' }]));
app.post('/api/admin/login', (_req, res) => res.json({ token: 'preview-only' }));
app.get('/api/admin/stats', (_req, res) => res.json({}));
process.env.POST_APP_SHELL_URL = 'http://127.0.0.1:5188/shell';
mountPostRoutes(app, (req, res, next) => { if (req.headers.authorization !== 'Bearer preview-only') return res.sendStatus(401); req.admin = { role: 'SUPER_ADMIN' }; next(); }, () => 'http://127.0.0.1:5188', store);
app.get('/api/*', (_req, res) => res.json([]));
app.use('/admin', express.static(path.join(root, 'admin/dist')));
app.use(express.static(path.join(root, 'www')));
const server = app.listen(5188, '127.0.0.1', () => console.log('Isolated news preview http://127.0.0.1:5188/news'));
const stop = () => { server.closeAllConnections(); server.close(() => { fs.rmSync(dir, { recursive: true, force: true }); process.exit(0); }); };
process.on('SIGINT', stop); process.on('SIGTERM', stop);
